"""add password reset tokens table

Revision ID: 152eeb9e0b02
Revises: 001_initial
Create Date: 2026-02-23 20:09:39.547310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '152eeb9e0b02'
down_revision: Union[str, Sequence[str], None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index('ix_prt_token_hash', 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_index('ix_prt_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.alter_column('tasks', 'assignment_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_tasks_assigned_active_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_status_active'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignment_rules_gin'), table_name='tasks', postgresql_using='gin')
    op.drop_index(op.f('ix_tasks_created_by'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_unassigned_active'), table_name='tasks', postgresql_where='((assigned_to IS NULL) AND (is_active = true))')
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.drop_index(op.f('ix_users_dept_exp_active'), table_name='users')
    op.drop_index(op.f('uq_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('uq_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_dept_exp_active'), 'users', ['department', 'experience_years', 'is_active'], unique=False)
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_unassigned_active'), 'tasks', ['is_active', 'created_at'], unique=False, postgresql_where='((assigned_to IS NULL) AND (is_active = true))')
    op.create_index(op.f('ix_tasks_created_by'), 'tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_tasks_assignment_rules_gin'), 'tasks', ['assignment_rules'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_tasks_assigned_status_active'), 'tasks', ['assigned_to', 'status', 'is_active'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_active_status'), 'tasks', ['assigned_to', 'is_active', 'status'], unique=False)
    op.alter_column('tasks', 'assignment_rules',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('ix_prt_user_id', table_name='password_reset_tokens')
    op.drop_index('ix_prt_token_hash', table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
